global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'microservices-ecs'
    environment: 'dev'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.111:8080']
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.249:8081']
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.98:8084']
  - job_name: 'favourite-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.197:8086']
  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.5:8761']
  - job_name: 'cloud-config'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.253:8888']
  - job_name: 'proxy-client'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.193:8087']

