global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'microservices-ecs'
    environment: 'dev'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloud-config'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.66:8888']
        labels:
          service: 'cloud-config'
          environment: 'dev'
  - job_name: 'proxy-client'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.250:8087']
        labels:
          service: 'proxy-client'
          environment: 'dev'
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.111:8080']
        labels:
          service: 'api-gateway'
          environment: 'dev'
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.20.249:8081']
        labels:
          service: 'user-service'
          environment: 'dev'
  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.10.5:8761']
        labels:
          service: 'service-discovery'
          environment: 'dev'
