apiVersion: v1
kind: Namespace
metadata:
  name: microservices-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices-prod
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    environment: shared
